/**
 * <Email> render mode — the official finisher results email.
 * Table-based, Outlook/Gmail-safe HTML generated by Elements.
 */
import {
  Email,
  Row,
  Column,
  ColumnLayouts,
  Heading,
  Paragraph,
  Button,
  Divider,
  Table,
  Social,
} from "@unlayer/react-elements";
import { raceData, splitsTableData, splitsTableHeaders } from "../lib/data";
import { colors, fonts } from "../lib/theme";
import { StatTile, FieldBar } from "../lib/tools";

const { event, runner, result } = raceData;

export default function ResultsEmail() {
  return (
    <Email
      backgroundColor={colors.mist}
      contentWidth="600px"
      previewText={`Official results: ${result.chipTime} — you finished the ${event.name}!`}
      fontFamily={fonts.body}
    >
      {/* Masthead */}
      <Row backgroundColor={colors.night} padding="22px 40px">
        <Column>
          <Paragraph
            color="#ffffff"
            fontSize="15px"
            fontWeight={800}
            fontFamily={fonts.display}
            textAlign="left"
            html={`FINISH LINE&nbsp;&nbsp;<span style="color:${colors.accent};">/</span>&nbsp;&nbsp;<span style="color:#9aa7b8;font-weight:500;">${event.name}</span>`}
          />
        </Column>
      </Row>

      {/* Hero */}
      <Row backgroundColor={colors.paper} padding="44px 40px 8px">
        <Column>
          <Paragraph
            color={colors.accent}
            fontSize="12px"
            fontWeight={700}
            letterSpacing="2px"
            textAlign="center"
            text="OFFICIAL RESULT · CHIP TIMED"
          />
          <Heading
            level="h1"
            fontFamily={fonts.display}
            fontSize="30px"
            lineHeight="38px"
            fontWeight={800}
            color={colors.ink}
            textAlign="center"
          >
            {`You did it, ${runner.firstName}.`}
          </Heading>
          <Paragraph color={colors.slate} fontSize="15px" lineHeight="24px" textAlign="center">
            {`${event.distance} · ${event.date} · ${event.location}`}
          </Paragraph>
        </Column>
      </Row>

      {/* Big time */}
      <Row backgroundColor={colors.paper} padding="8px 40px 4px">
        <Column>
          <Heading
            level="h2"
            fontFamily={fonts.display}
            fontSize="56px"
            lineHeight="64px"
            fontWeight={800}
            color={colors.ink}
            textAlign="center"
            text={result.chipTime}
          />
          <Paragraph color={colors.faint} fontSize="13px" textAlign="center">
            {`Chip time · Gun time ${result.gunTime} · Avg pace ${result.avgPace} /km · Bib #${runner.bib}`}
          </Paragraph>
        </Column>
      </Row>

      {/* Placement tiles — custom StatTile tool */}
      <Row layout={ColumnLayouts.ThreeEqual} backgroundColor={colors.paper} padding="18px 32px 6px">
        <Column padding="0 6px">
          <StatTile
            value={`#${result.overallPlace}`}
            label="Overall"
            sub={`of ${result.overallField.toLocaleString()}`}
          />
        </Column>
        <Column padding="0 6px">
          <StatTile
            value={`#${result.genderPlace}`}
            label="Women"
            sub={`of ${result.genderField.toLocaleString()}`}
          />
        </Column>
        <Column padding="0 6px">
          <StatTile
            value={`#${result.divisionPlace}`}
            label={runner.division}
            sub={`of ${result.divisionField}`}
            valueColor={colors.accent}
          />
        </Column>
      </Row>

      {/* Field bar — custom FieldBar tool */}
      <Row backgroundColor={colors.paper} padding="16px 40px 4px">
        <Column>
          <FieldBar
            percent={result.fasterThanPct}
            label={`You ran faster than ${result.fasterThanPct}% of today's field — and negative-split the course by ${result.negativeSplit}.`}
          />
        </Column>
      </Row>

      {/* Splits */}
      <Row backgroundColor={colors.paper} padding="24px 40px 8px">
        <Column>
          <Heading
            level="h3"
            fontFamily={fonts.display}
            fontSize="18px"
            fontWeight={700}
            color={colors.ink}
            text="Your splits"
          />
          <Table
            headers={[...splitsTableHeaders]}
            data={splitsTableData}
            contentFontSize="13px"
            headerFontSize="13px"
            contentPadding="8px 10px"
            headerPadding="8px 10px"
            headerBackgroundColor={colors.night}
            headerColor="#ffffff"
            contentColor={colors.ink}
            stripedRows
            stripedRowsBackgroundColor={colors.mist}
            border={{
              borderTopWidth: "0px",
              borderRightWidth: "0px",
              borderBottomWidth: "1px",
              borderLeftWidth: "0px",
              borderBottomColor: colors.line,
              borderBottomStyle: "solid",
            }}
          />
        </Column>
      </Row>

      {/* CTAs */}
      <Row layout={ColumnLayouts.TwoEqual} backgroundColor={colors.paper} padding="16px 40px 8px">
        <Column padding="0 6px">
          <Button
            href={event.certificateUrl}
            backgroundColor={colors.accent}
            color="#ffffff"
            fontWeight={700}
            fontSize="14px"
            width="100%"
            padding="14px 10px"
            borderRadius="8px"
          >
            Download certificate
          </Button>
        </Column>
        <Column padding="0 6px">
          <Button
            href={event.photosUrl}
            backgroundColor={colors.night}
            color="#ffffff"
            fontWeight={700}
            fontSize="14px"
            width="100%"
            padding="14px 10px"
            borderRadius="8px"
          >
            View race photos
          </Button>
        </Column>
      </Row>

      <Row backgroundColor={colors.paper} padding="8px 40px 36px">
        <Column>
          <Paragraph color={colors.faint} fontSize="12px" lineHeight="18px" textAlign="center">
            {`Result verification ID ${result.verificationId}. Times are official once certified by the race referee.`}
          </Paragraph>
        </Column>
      </Row>

      {/* Footer */}
      <Row backgroundColor={colors.mist} padding="28px 40px 8px">
        <Column>
          <Social
            icons={[
              { name: "Instagram", url: "https://instagram.com/example" },
              { name: "X", url: "https://x.com/example" },
              { name: "Facebook", url: "https://facebook.com/example" },
            ]}
            iconType="circle"
            iconSize={30}
            spacing={10}
            align="center"
          />
          <Paragraph color={colors.faint} fontSize="12px" lineHeight="18px" textAlign="center">
            {`${event.name} · ${event.location}`}
          </Paragraph>
          <Paragraph
            color={colors.faint}
            fontSize="12px"
            lineHeight="18px"
            textAlign="center"
            html={`You received this because you ran with bib #${runner.bib}. <a href="https://example.com/preferences" style="color:${colors.slate};">Email preferences</a>`}
          />
        </Column>
      </Row>

      <Row backgroundColor={colors.mist} padding="0 40px 30px">
        <Column>
          <Divider borderTopWidth="1px" borderTopColor={colors.line} width="60%" />
        </Column>
      </Row>
    </Email>
  );
}
